1.what is a python libraray? why do we use python libraries?

A Python library is a collection of pre-written code, functions, classes, and modules that provides functionalities to help programmers perform common tasks without having to write code from scratch. Libraries in Python encapsulate reusable code into packages that you can import and use in your own programs.





 Uses of  Python Libraries?
Code Reusability:

Save Time: Libraries provide pre-built functionality that saves you from having to write and debug code from scratch.
Avoid Reinventing the Wheel: You can leverage existing solutions for common problems and focus on implementing the unique aspects of your project.
Enhanced Productivity:

Faster Development: With libraries handling common tasks, you can develop software faster.
Focus on Core Logic: Libraries allow you to concentrate on the specific logic of your application, rather than on low-level details.
Improved Code Quality:

Tested and Reliable: Libraries are often well-tested and optimized, providing robust and reliable solutions.
Community Support: Many libraries are maintained by the community or organizations, ensuring they are up-to-date and reliable.
Access to Specialized Functionality:

Complex Operations: Libraries offer advanced features for complex tasks such as data analysis (pandas), machine learning (scikit-learn), web development (Flask, Django), and more.
External Integrations: Libraries can provide functionality for integrating with external services and APIs.
Consistency and Best Practices:

Standard Practices: Libraries often follow best practices and coding standards, helping ensure consistency in how tasks are handled.
Documentation: Many libraries come with comprehensive documentation that helps you understand how to use the functionality they provide.

In [ ]:
#example of numpy librarary
# to install libraray we use
#pip install   <libraray name>

#to import libraray
#we use import library name

import numpy as np

2. What is the difference between Numpy array and List

Both NumPy arrays and Python lists are used to store collections of items, but they differ significantly in their functionality, performance, and use cases.

NumPy Array vs. Python List
1. Performance
NumPy Array:

Efficiency: NumPy arrays are more efficient for numerical operations because they are implemented in C and use contiguous memory. This makes them faster for operations on large datasets.
Vectorized Operations: NumPy supports vectorized operations, meaning that operations are performed on the whole array at once rather than using Python loops, which leads to faster execution.
Python List:

Performance: Python lists are less efficient for numerical operations. They are general-purpose containers that store elements as Python objects, leading to slower execution for large-scale numerical computations.
Element-wise Operations: Operations on lists are typically done using loops and are less optimized compared to NumPy’s vectorized operations.
2. Homogeneity
NumPy Array:

Homogeneous: NumPy arrays require all elements to be of the same data type (e.g., all integers or all floats). This allows for efficient storage and computation.
Python List:

Heterogeneous: Python lists can contain elements of different types (e.g., integers, floats, strings), which provides flexibility but can lead to inefficiencies in numerical computations.
3. Functionality
NumPy Array:

Mathematical Functions: NumPy provides a wide range of mathematical and statistical functions (e.g., mean, median, standard deviation) that operate efficiently on arrays.
Multidimensional Arrays: NumPy supports multidimensional arrays (e.g., matrices) and provides functions for operations on these arrays.
Broadcasting: NumPy supports broadcasting, allowing operations between arrays of different shapes.
Python List:

Basic Operations: Python lists offer basic operations like appending, slicing, and concatenation but lack built-in support for advanced mathematical operations.
No Built-in Support for Multidimensional Arrays: Python lists can be nested to represent multidimensional arrays, but this is less efficient and requires manual handling.
4. Memory Consumption
NumPy Array:

Memory Efficiency: NumPy arrays are more memory-efficient due to their fixed-size data type and contiguous memory allocation.
Python List:

Memory Overhead: Python lists have higher memory overhead because they store references to objects and each element is a separate Python object.
5. Ease of Use
NumPy Array:

Learning Curve: NumPy arrays might have a steeper learning curve due to their extensive functionality and the need to understand array operations and broadcasting.
Library Dependency: Requires importing the NumPy library (import numpy as np).
Python List:

Built-in: Python lists are built into the language and require no additional libraries. They are easy to use for basic tasks.
General-purpose: They are more flexible and suitable for general-purpose tasks where numerical computations are not a primary concern.

In [ ]:
li=[1,2,3,4,5]

a=np.array(li)
print(type(li))
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

a=np.array(li)

print('shape:',a.shape)
print('size:',a.size)
print('dimension:',a.ndim)

shape: (3, 4)
size: 12
dimension: 2


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a=np.array(li)

#to access first row

a[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

a=np.array(li)

#to access the element at the third row and fourth column from the given numpy array

a[2,3]



12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
li=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a=np.array(li)

#to extract all odd-indexed elements from the given numpy array



odd_indexed_elements = a[::2]

print("Original Array:", a)
print("Odd-Indexed Elements:", odd_indexed_elements)

Original Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Odd-Indexed Elements: [[ 1  2  3  4]
 [ 9 10 11 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [ ]:
import numpy as np

# Generate a 3x3 matrix with random values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 Matrix:")
print(random_matrix)


Random 3x3 Matrix:
[[0.60933626 0.26888368 0.27617515]
 [0.33630579 0.09546477 0.18725999]
 [0.09829349 0.98281605 0.32693873]]


8. Describe the difference between np.random.rand and np.random.randin

The functions np.random.rand and np.random.randint in NumPy are both used to generate random numbers, but they serve different purposes and produce different types of outputs.

1. np.random.rand
Purpose: Generates an array of random numbers from a uniform distribution over the interval
[
0
,
1
).
Output: The output is an array of floating-point numbers between 0 (inclusive) and 1 (exclusive).
Usage:
You can specify the dimensions of the array as arguments.
The numbers are uniformly distributed, meaning each number in the interval
[
0
,
1
) has an equal chance of being generated.


2. np.random.randint
Purpose: Generates random integers from a specified range.

Output: The output is an array of integers within a specified range.
Usage:
You need to specify the lower bound (inclusive) and upper bound (exclusive) of the range, and optionally, the shape of the output array.
You can generate either a single integer or an array of integers.




np.random.rand generates floating-point numbers in the interval
[
0
,
1
).
np.random.randint generates integers within a specified range.
Range of Values:

np.random.rand always generates numbers between 0 and 1.

np.random.randint generates integers between a specified lower and upper bound.
Typical Use Cases:

np.random.rand is typically used when you need random decimal numbers, often for tasks involving probabilities, simulations, or initializing weights in neural networks.
np.random.randint is useful when you need discrete values, such as indices for sampling, generating random labels, or creating random subsets.








In [ ]:
#code:
import numpy as np

# Generating  a 2x3 array of random integers between 5 (inclusive) and 10 (exclusive)
random_integers = np.random.randint(5, 10, size=(2, 3))
print(random_integers)


[[8 8 5]
 [8 9 8]]


In [ ]:
import numpy as np

# Generate a 2x3 array of random integers between 5 (inclusive) and 10 (exclusive)
random = np.random.rand(2, 3)
print(random)


[[0.82842437 0.20516443 0.49708591]
 [0.07847873 0.08683237 0.51016603]]


9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]

To increase the dimension of a given NumPy array, you can use the np.expand_dims function or by reshaping the array.

In [ ]:
import numpy as np

# Original 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])


# Add a new axis (increase dimension)
# Adding a new axis along the first dimension
new_arr = np.expand_dims(arr, axis=0)

print("Array with increased dimension:")
print(new_arr)
print("Shape:", new_arr.shape)


Array with increased dimension:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Shape: (1, 3, 4)


using reshape()

In [ ]:
# Reshape to increase dimension
# Adding a new dimension to make it a 3D array
new_arr_reshape = arr.reshape(1, 3, 4)

print("Array reshaped to increase dimension:")
print(new_arr_reshape)
print("Shape:", new_arr_reshape.shape)


Array reshaped to increase dimension:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Shape: (1, 3, 4)


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

To transpose a 2D array in NumPy, you can use the numpy.transpose() function or the .T attribute. Transposing an array means flipping it over its diagonal, so the rows become columns and the columns become rows.

In [ ]:
import numpy as np

# Original 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])


In [ ]:
# Transpose the array using .T
transposed_arr = arr.T

print("Transposed Array using .T:")
print(transposed_arr)


Transposed Array using .T:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


using program

11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

 Index wise multiplication
 Matrix multiplication
 Add both the matrix
 Subtract matrix B from a
 Divide Matrix B by a

In [ ]:
import numpy as np

# Define the matrices
A2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Index-wise (element-wise) multiplication
elementwise_multiplication = A2 * B2
print("Element-wise Multiplication:\n", elementwise_multiplication)

# Matrix multiplication (dot product)
matrix_multiplication = np.dot(A2, B2.T)  # Transpose B2 for correct dimensions
print("\nMatrix Multiplication:\n", matrix_multiplication)

# Add both matrices
matrix_addition = A2 + B2
print("\nMatrix Addition:\n", matrix_addition)

# Subtract matrix B2 from A2
matrix_subtraction = A2 - B2
print("\nMatrix Subtraction (A2 - B2):\n", matrix_subtraction)

# Divide Matrix B2 by A2
matrix_division = B2 / A2
print("\nMatrix Division (B2 / A2):\n", matrix_division)


Element-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Subtraction (A2 - B2):
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix Division (B2 / A2):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12.  Which function in Numpy can be used to swap the byte order of an array

In NumPy, the function used to swap the byte order of an array is numpy.ndarray.byteswap().

This function changes the byte order of the elements in the array, making it useful when dealing with data that has a different endianness than the system's native endianness.

In [ ]:
import numpy as np

# Creating an array
arr = np.array([1, 256, 1024], dtype=np.int32)

# Printing the original array
print("Original array:", arr)

# Swapping the byte order
swapped_arr = arr.byteswap()

# Printing the swapped array
print("Byte-swapped array:", swapped_arr)


Original array: [   1  256 1024]
Byte-swapped array: [16777216    65536   262144]


13.  What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to calculate the inverse of a square matrix. The inverse of a matrix
𝐴
 is another matrix
𝐴
−
1

  such that when
𝐴
 is multiplied by
𝐴
−
1

 , it results in the identity matrix
𝐼
I. This can be expressed as:


A×A
−1
 =A
−1
 ×A=I

Significance of np.linalg.inv
Solving Linear Systems: One of the primary applications of matrix inversion is in solving systems of linear equations. If you have a system of equations
𝐴
𝑋
=
𝐵
AX=B, where
𝐴
is a square matrix,
𝑋
is a vector of variables, and
𝐵
 is a vector of constants, you can solve for
𝑋
by multiplying both sides by the inverse of

A:

𝑋
=
𝐴
−
1
𝐵

Matrix Algebra: The inverse matrix is fundamental in various matrix algebra operations, especially in fields like linear algebra, control theory, and statistics.

Transformations: In graphics and geometric transformations, matrix inversion is used to reverse transformations such as scaling, rotation, and translation.

Theoretical Applications: In theory, the inverse of a matrix is key in proofs and derivations involving linear transformations and eigenvalues.

Important Notes

Existence: Not all matrices have an inverse. A matrix has an inverse if and only if it is square (same number of rows and columns) and its determinant is non-zero.

Computational Considerations: Calculating the inverse of a matrix can be computationally expensive, especially for large matrices. In some cases, it might be more efficient to use methods like LU decomposition or direct solvers rather than explicitly calculating the inverse.


In [ ]:
import numpy as np

# Define a square matrix A
A = np.array([[1, 2], [3, 4]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

print("Inverse of A:")
print(A_inv)

# Verify by multiplying A with its inverse to get the identity matrix
I = np.dot(A, A_inv)
print("Identity matrix:")
print(I)



Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]
Identity matrix:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an existing array without altering its data. Essentially, it rearranges the elements of the array to fit into a new shape that you specify.

Functionality
Input Array: np.reshape takes an input array and reshapes it into a new shape that you specify through a tuple.

Shape Compatibility: The total number of elements in the original array must match the total number of elements in the new shape. For example, you cannot reshape an array of size 6 into a shape that has 7 elements.

np.reshape(a, newshape, order='C')


a: The input array you want to reshape.
newshape: A tuple that defines the new shape of the array. One dimension can be -1, which means that dimension is inferred from the other dimensions.
order: (Optional) This argument determines the order of reading/writing elements ('C' for row-major (C-style), 'F' for column-major (Fortran-style)). The default is 'C'.

In [ ]:
import numpy as np

# Original 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 2x3 array
reshaped_arr = np.reshape(arr, (2, 3))

print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows operations on arrays of different shapes. It automatically expands the smaller array(s) to match the shape of the larger array so that element-wise operations can be performed without explicitly copying the data. This feature is especially useful in performing mathematical operations on arrays of different sizes, such as addition, subtraction, multiplication, etc.

How Broadcasting Works
Broadcasting follows specific rules to determine how the smaller array can be expanded to perform operations with a larger array:

Aligning Dimensions: NumPy compares the shapes of the two arrays element by element, starting from the rightmost dimension.

Shape Compatibility Rules:

If the two dimensions are equal, they are compatible.

If one of the dimensions is 1, it is "stretched" to match the other dimension.
If the dimensions are different and neither is 1, the arrays are not compatible for broadcasting.

Expanding the Smaller Array: Once the dimensions are aligned, NumPy virtually expands the smaller array along the dimension(s) where it has size 1 to match the size of the corresponding dimension of the larger array. This expansion is done without actually replicating the data, making broadcasting memory-efficient.

Benefits of Broadcasting
Memory Efficiency: Broadcasting avoids the need to explicitly replicate data, saving memory and reducing computational overhead.
Conciseness: It allows for more concise code, as you can perform operations on arrays of different shapes without needing to manually reshape or repeat arrays.
Performance: Broadcasting operations are generally optimized and can be faster than manually expanding arrays.
When Broadcasting Fails
If the shapes of the arrays do not satisfy the broadcasting rules, NumPy will raise a ValueError, indicating that the operands could not be broadcasted together.

Summary
Broadcasting is a key feature in NumPy that simplifies array operations by automatically handling different shapes, making it easier to write efficient and concise code.

In [ ]:
#Adding Two Arrays of Different Shapes:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2

print(result)


[[11 22 33]
 [14 25 36]]
